# 生产环境：端口80（默认端口），数据库连远程，不打印SQL
server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://192.168.1.100:3306/prod_db?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: prod_user
    password: prod_pass123
  redis:
    host: 192.168.1.100

# 生产环境关闭SQL打印，提高性能
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl